### ISSUE TITLE
docker with GPU

### ISSUE THREAD

**Issue by Michael-H777** [SynthRAD2023/algorithm-template#2]
Hello all, 

Thanks in advance for your time. 

Im very new to docker, and is following the readme to build my docker to submit to the challenge. 

I've had lots of problem to get my model to run on my gpu on ubuntu 22. I was able to modify the dockerfile and use 
`FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime` 
instead of 
`FROM python:3.9-slim`

had to also install gcc in dockerfile via 
`
USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
USER algorithm
` 
to get numpy to build. 

however, now when initializing my network on gpu, python says 
`
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
`
the solution online asks me to use a nvidia-docker instead, which raised some concern. 

another potential solution is to add the `--gpus all` argument to the `docker run` in `test.sh`, but the file explicitly said to not change any parameter. 

my question is 
1. what is the proper way to build the docker to that my model runs on gpu? 
2. should i use this recommended nvidia-docker `sudo apt-get install -y nvidia-docker2` instead of the regular docker? 

below is the dockerfile, commended parts is the original dockerfile provided. 

thanks a lot! 

```
# FROM python:3.9-slim

# ARG task_type

# ENV TASK_TYPE=$task_type
# ENV EXECUTE_IN_DOCKER=1

# RUN groupadd -r algorithm && useradd -m --no-log-init -r -g algorithm algorithm

# RUN mkdir -p /opt/algorithm /input /output \
#     && chown algorithm:algorithm /opt/algorithm /input /output

# USER algorithm

# WORKDIR /opt/algorithm

# ENV PATH="/home/algorithm/.local/bin:${PATH}"

# RUN python -m pip install --user -U pip

# COPY --chown=algorithm:algorithm requirements.txt /opt/algorithm/
# RUN python -m pip install --user -rrequirements.txt

# COPY --chown=algorithm:algorithm .env /opt/algorithm/
# COPY --chown=algorithm:algorithm process.py /opt/algorithm/
# COPY --chown=algorithm:algorithm base_algorithm.py /opt/algorithm/

# ENTRYPOINT python -m process $0 $@

# Start from a PyTorch image
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

ARG task_type

ENV TASK_TYPE=$task_type
ENV EXECUTE_IN_DOCKER=1

RUN groupadd -r algorithm && useradd -m --no-log-init -r -g algorithm algorithm

RUN mkdir -p /opt/algorithm /input /output \
    && chown algorithm:algorithm /opt/algorithm /input /output

USER algorithm

WORKDIR /opt/algorithm

USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
USER algorithm

ENV PATH="/home/algorithm/.local/bin:${PATH}"

RUN python -m pip install --user -U pip

COPY --chown=algorithm:algorithm requirements.txt /opt/algorithm/
RUN python -m pip install --user -r requirements.txt

COPY --chown=algorithm:algorithm .env /opt/algorithm/
COPY --chown=algorithm:algorithm process.py /opt/algorithm/
COPY --chown=algorithm:algorithm base_algorithm.py /opt/algorithm/

ENTRYPOINT ["python", "-m", "process"]
```

system info: 

Docker version 23.0.6, build ef23cbc

Linux version 5.15.0-71-generic (buildd@lcy02-amd64-044) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023

**Comment by surajpaib** [comment]
Hi @Michael-H777 

I'm sorry to hear that you've been having trouble with GPU support on docker. 

I've added some documentation in the README.md https://github.com/SynthRAD2023/algorithm-template#to-run-your-docker-locally-with-gpu-support
that should help you add the nvidia container toolkit to your docker installation. `nvidia-docker2` is deprecated now and should not be used.

Once you install the toolkit, you should be able to run the test by running the newly added `test_gpu.sh`. This does exactly as you mentioned by adding the `--gpus=all` to the `docker run` command. Grand challenge does not recommend changing those options but adding GPUs there should not be a problem.

P.S You do not need to actually modify the `Dockerfile` to add dependencies for the GPU. Adding `torch` in the `requirements.txt` file should install GPU supported torch by default

Let us know if you have any more questions and good luck with your submission!

**Comment by surajpaib** [comment]
@Michael-H777 Let me know if your issue is resolved and I can go ahead and close this!

**Comment by Michael-H777** [comment]
Hi, thanks for the update! 

i had to make some minor changes, but the test_gpu.sh worked. 

1. i want able to install via the link provided, i had to 
```
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
```
2. once the nvidia-container-toolkit was installed, i needed to add 

`COPY weights.pth /app/` 

into the docker file, so that the process.py can access the weights via '/app/weights.pth' 

Michael

**Comment by surajpaib** [comment]
Hi Michael,

For 1. I want to double-check the link you used to try and install the container toolkit. The one on the README https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html mentions the exact command you have shared above.

2. Yes, you will need to push the weights in the docker. We suggested moving it to `/opt/algorithm` in the README so you can access it in the same folder as the process.py. But you are of course free to put it anywhere. 

Closing this issue as I think everything looks in order here. If you have any other issues, feel free to open new issues! Good luck.
